// GENERATED by scripts/build-portfolio.js — do not edit by hand.
// Add images to /public and run `yarn portfolio` to refresh.
const WORKS = [
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Ampoule",
    "images": [
      "/studio/ampoule1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Biji Kopi",
    "images": [
      "/studio/biji kopi.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Bodylotion",
    "images": [
      "/studio/bodylotion1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Bodylotion",
    "images": [
      "/studio/bodylotion2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Bodymist",
    "images": [
      "/studio/bodymist1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Bodyscrub",
    "images": [
      "/studio/bodyscrub1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Bodywash",
    "images": [
      "/studio/bodywash1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Botol Kaleng",
    "images": [
      "/studio/botol kaleng.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Botol Minum",
    "images": [
      "/studio/botol minum.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Brownie",
    "images": [
      "/studio/brownie1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Candle",
    "images": [
      "/studio/candle1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Casing",
    "images": [
      "/studio/casing1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Cctv",
    "images": [
      "/studio/cctv1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Cleanser",
    "images": [
      "/studio/cleanser1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Cleanser",
    "images": [
      "/studio/cleanser2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Cup",
    "images": [
      "/studio/cup1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Dispenser",
    "images": [
      "/studio/dispenser1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Earphone",
    "images": [
      "/studio/earphone1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Facewash",
    "images": [
      "/studio/facewash1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Hairdryer",
    "images": [
      "/studio/hairdryer1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Jamtangan",
    "images": [
      "/studio/jamtangan1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Jamtangan",
    "images": [
      "/studio/jamtangan2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Kacamata",
    "images": [
      "/studio/kacamata1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Kaos",
    "images": [
      "/studio/kaos1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Keyboard",
    "images": [
      "/studio/keyboard1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Lipstick",
    "images": [
      "/studio/lipstick1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Matchapowder",
    "images": [
      "/studio/matchapowder1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Micellerwater",
    "images": [
      "/studio/micellerwater1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Moisturizer",
    "images": [
      "/studio/moisturizer1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Moisturizer",
    "images": [
      "/studio/moisturizer2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Parfume",
    "images": [
      "/studio/parfume.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume10.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume3.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume4.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume5.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume6.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume7.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume8.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Perfume",
    "images": [
      "/studio/perfume9.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Sepatu",
    "images": [
      "/studio/sepatu1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Sepatu",
    "images": [
      "/studio/sepatu2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Serum",
    "images": [
      "/studio/serum.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Serum",
    "images": [
      "/studio/serum2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Serum",
    "images": [
      "/studio/serum3.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Serum",
    "images": [
      "/studio/serum4.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Serum",
    "images": [
      "/studio/serum5.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skinare Ampoule Studio",
    "images": [
      "/studio/skinare-ampoule studio.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Ampoule",
    "images": [
      "/studio/skincare-ampoule.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Facewash",
    "images": [
      "/studio/skincare-facewash.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Moisturizer Birutema",
    "images": [
      "/studio/skincare-moisturizer birutema.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Serum",
    "images": [
      "/studio/skincare-serum.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Serum",
    "images": [
      "/studio/skincare-serum2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Serum",
    "images": [
      "/studio/skincare-serum3.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Serum",
    "images": [
      "/studio/skincare-serum4.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Set",
    "images": [
      "/studio/skincare-set.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Skincare Set",
    "images": [
      "/studio/skincare-set2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Speaker",
    "images": [
      "/studio/speaker1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Sunscreen",
    "images": [
      "/studio/sunscreen.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Sunscreen",
    "images": [
      "/studio/sunscreen1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Sunscreen",
    "images": [
      "/studio/sunscreen2.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Tas",
    "images": [
      "/studio/tas1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Toner",
    "images": [
      "/studio/toner1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Tumbler",
    "images": [
      "/studio/tumbler1.webp"
    ]
  },
  {
    "type": "studio",
    "cat": "Foto Studio",
    "title": "Tumbler",
    "images": [
      "/studio/tumbler2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Babylotion",
    "images": [
      "/marketplace/babylotion.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Babyoil",
    "images": [
      "/marketplace/babyoil1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Bodyscrub",
    "images": [
      "/marketplace/bodyscrub1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Casing",
    "images": [
      "/marketplace/casing1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Clay",
    "images": [
      "/marketplace/clay1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Facemist",
    "images": [
      "/marketplace/facemist1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Facewash",
    "images": [
      "/marketplace/facewash1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Facialwash",
    "images": [
      "/marketplace/facialwash1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Foundation",
    "images": [
      "/marketplace/foundation1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Gelang",
    "images": [
      "/marketplace/gelang1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Hairpowder",
    "images": [
      "/marketplace/hairpowder1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Hoodie",
    "images": [
      "/marketplace/hoodie1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Jilbab",
    "images": [
      "/marketplace/jilbab.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Kipasangin",
    "images": [
      "/marketplace/kipasangin1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Koper",
    "images": [
      "/marketplace/koper1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Lilin",
    "images": [
      "/marketplace/lilin1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Liptint",
    "images": [
      "/marketplace/liptint1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Makeup",
    "images": [
      "/marketplace/makeup1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Moisturizer",
    "images": [
      "/marketplace/moisturizer1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Parfume",
    "images": [
      "/marketplace/parfume1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Parfume",
    "images": [
      "/marketplace/parfume2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Perfume",
    "images": [
      "/marketplace/perfume3.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Powerbank",
    "images": [
      "/marketplace/powerbank1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Serum",
    "images": [
      "/marketplace/serum2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Shirt",
    "images": [
      "/marketplace/shirt1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Shirt",
    "images": [
      "/marketplace/shirt2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Moisturizer",
    "images": [
      "/marketplace/skincare-moisturizer.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Serum",
    "images": [
      "/marketplace/skincare-serum.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Sunscreen",
    "images": [
      "/marketplace/skincare-sunscreen.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Toneuplotion",
    "images": [
      "/marketplace/skincare-toneuplotion.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Slingbag",
    "images": [
      "/marketplace/slingbag1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Susncreen",
    "images": [
      "/marketplace/susncreen1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Tas",
    "images": [
      "/marketplace/tas1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Toner",
    "images": [
      "/marketplace/toner1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Toner",
    "images": [
      "/marketplace/toner2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Topi",
    "images": [
      "/marketplace/topi1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Tumbler",
    "images": [
      "/marketplace/tumbler1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Botol",
    "images": [
      "/gallery/marketplace/botol1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Headset",
    "images": [
      "/gallery/marketplace/headset1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Jamtangan",
    "images": [
      "/gallery/marketplace/jamtangan1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Jamtangan",
    "images": [
      "/gallery/marketplace/jamtangan2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Lipstick",
    "images": [
      "/gallery/marketplace/lipstick1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Lipstick",
    "images": [
      "/gallery/marketplace/lipstick2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Perfume",
    "images": [
      "/gallery/marketplace/perfume1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Perfume",
    "images": [
      "/gallery/marketplace/perfume2.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Perfume",
    "images": [
      "/gallery/marketplace/perfume3.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Sepatu",
    "images": [
      "/gallery/marketplace/sepatu1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Ampoule",
    "images": [
      "/gallery/marketplace/skincare-ampoule.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Ampoule",
    "images": [
      "/gallery/marketplace/skincare-ampoule1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Moisturizer",
    "images": [
      "/gallery/marketplace/skincare-moisturizer.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Serum",
    "images": [
      "/gallery/marketplace/skincare-serum.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Sunscreen",
    "images": [
      "/gallery/marketplace/skincare-sunscreen.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Skincare Toneuplotion",
    "images": [
      "/gallery/marketplace/skincare-toneuplotion.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Sunscreen",
    "images": [
      "/gallery/marketplace/sunscreen.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Sunscreen",
    "images": [
      "/gallery/marketplace/sunscreen1.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Tas",
    "images": [
      "/gallery/marketplace/tas.webp"
    ]
  },
  {
    "type": "marketplace",
    "cat": "Etalase Marketplace",
    "title": "Tas",
    "images": [
      "/gallery/marketplace/tas1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Bodycare Bodywash",
    "images": [
      "/gallery/skincare/bodycare-bodywash.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Bodycare Scrubtestimoni",
    "images": [
      "/gallery/skincare/bodycare-scrubtestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Bodycare Shampootestimoni",
    "images": [
      "/gallery/skincare/bodycare-shampootestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Cleanser",
    "images": [
      "/gallery/skincare/cleanser.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Cleanser",
    "images": [
      "/gallery/skincare/cleanser1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Cleanser",
    "images": [
      "/gallery/skincare/cleanser2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Cleanser",
    "images": [
      "/gallery/skincare/cleanser3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Cleanser",
    "images": [
      "/gallery/skincare/cleanser4.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Cleanser",
    "images": [
      "/gallery/skincare/cleanser5.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Difusserlaunch",
    "images": [
      "/gallery/skincare/difusserlaunch1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Lipstick",
    "images": [
      "/gallery/skincare/lipstick1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Lipstick",
    "images": [
      "/gallery/skincare/lipstick2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Facewashlaunch",
    "images": [
      "/gallery/skincare/skincare-facewashlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Facewashlaunch",
    "images": [
      "/gallery/skincare/skincare-facewashlaunch2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Facewashtestimoni",
    "images": [
      "/gallery/skincare/skincare-facewashtestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Moisturizer",
    "images": [
      "/gallery/skincare/skincare-moisturizer.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Moisturizer",
    "images": [
      "/gallery/skincare/skincare-moisturizer1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum4.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum5.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum6.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum7.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serum",
    "images": [
      "/gallery/skincare/skincare-serum8.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serumlaunch",
    "images": [
      "/gallery/skincare/skincare-serumlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serumlaunch",
    "images": [
      "/gallery/skincare/skincare-serumlaunch2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serumlaunch",
    "images": [
      "/gallery/skincare/skincare-serumlaunch3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serumtestimoni",
    "images": [
      "/gallery/skincare/skincare-serumtestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Serumtestimoni",
    "images": [
      "/gallery/skincare/skincare-serumtestimoni2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Toner",
    "images": [
      "/gallery/skincare/skincare-toner1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincare Tonerlaunch",
    "images": [
      "/gallery/skincare/skincare-tonerlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincarelaunch",
    "images": [
      "/gallery/skincare/skincarelaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Skincarelaunch",
    "images": [
      "/gallery/skincare/skincarelaunch1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Sunscreen",
    "images": [
      "/gallery/skincare/sunscreen.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Sunscreen",
    "images": [
      "/gallery/skincare/sunscreen1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Testimoni Bodylotion",
    "images": [
      "/gallery/skincare/testimoni-bodylotion.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Skincare",
    "title": "Testimoni Skincare",
    "images": [
      "/gallery/skincare/testimoni-skincare.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Makanan Crunch",
    "images": [
      "/gallery/fnb/makanan-crunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Makanan Crunch",
    "images": [
      "/gallery/fnb/makanan-crunch2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Makanan Sambal",
    "images": [
      "/gallery/fnb/makanan-sambal.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Makanan",
    "images": [
      "/gallery/fnb/makanan.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Minuman Bery",
    "images": [
      "/gallery/fnb/minuman-bery.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Minuman Cup",
    "images": [
      "/gallery/fnb/minuman-cup.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Minuman Kaleng",
    "images": [
      "/gallery/fnb/minuman-kaleng.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Minuman Kalengtea",
    "images": [
      "/gallery/fnb/minuman-kalengtea.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Minuman Kopi",
    "images": [
      "/gallery/fnb/minuman-kopi.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Makanan & Minuman",
    "title": "Minuman Matcha",
    "images": [
      "/gallery/fnb/minuman-matcha.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Aksesoris",
    "images": [
      "/gallery/fashion/aksesoris.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Fashion Baju",
    "images": [
      "/gallery/fashion/fashion-baju.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Fashion Shirt",
    "images": [
      "/gallery/fashion/fashion-shirt.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Jamtangan",
    "images": [
      "/gallery/fashion/jamtangan1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Jamtangan",
    "images": [
      "/gallery/fashion/jamtangan2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Sepatu",
    "images": [
      "/gallery/fashion/sepatu1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Tas",
    "images": [
      "/gallery/fashion/tas.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Tas",
    "images": [
      "/gallery/fashion/tas1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Testimoni Hiljab",
    "images": [
      "/gallery/fashion/testimoni-hiljab.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Fashion",
    "title": "Testimoni Kaos",
    "images": [
      "/gallery/fashion/testimoni-kaos.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Parfum",
    "title": "Parfumlaunch",
    "images": [
      "/gallery/parfum/parfumlaunch1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Parfum",
    "title": "Perfume",
    "images": [
      "/gallery/parfum/perfume1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Parfum",
    "title": "Perfume",
    "images": [
      "/gallery/parfum/perfume2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Parfum",
    "title": "Perfume",
    "images": [
      "/gallery/parfum/perfume3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Parfum",
    "title": "Scent Candle",
    "images": [
      "/gallery/parfum/scent-candle.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Aksesoris",
    "images": [
      "/aksesoris.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Bodycare Bodywash",
    "images": [
      "/bodycare-bodywash.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Bodycare Scrubtestimoni",
    "images": [
      "/bodycare-scrubtestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Bodycare Shampootestimoni",
    "images": [
      "/bodycare-shampootestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Botol",
    "images": [
      "/botol1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Cleanser",
    "images": [
      "/cleanser1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Cleanser",
    "images": [
      "/cleanser2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Cleanser",
    "images": [
      "/cleanser3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Cleanser",
    "images": [
      "/cleanser4.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Cleanser",
    "images": [
      "/cleanser5.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Cleanser",
    "images": [
      "/cleanser6.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Difusserlaunch",
    "images": [
      "/difusserlaunch1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Fashion Baju",
    "images": [
      "/fashion-baju.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Fashion Shirt",
    "images": [
      "/fashion-shirt.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Headset",
    "images": [
      "/headset1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Jamtangan",
    "images": [
      "/jamtangan1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Jamtangan",
    "images": [
      "/jamtangan2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Lipstick",
    "images": [
      "/lipstick1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Lipstick",
    "images": [
      "/lipstick2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Makanan Crunch",
    "images": [
      "/makanan-crunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Makanan Crunch",
    "images": [
      "/makanan-crunch2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Makanan Sambal",
    "images": [
      "/makanan-sambal.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Makanan",
    "images": [
      "/makanan.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Minuman Bery",
    "images": [
      "/minuman-bery.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Minuman Cup",
    "images": [
      "/minuman-cup.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Minuman Kaleng",
    "images": [
      "/minuman-kaleng.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Minuman Kalengtea",
    "images": [
      "/minuman-kalengtea.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Minuman Kopi",
    "images": [
      "/minuman-kopi.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Minuman Matcha",
    "images": [
      "/minuman-matcha.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Parfumlaunch",
    "images": [
      "/parfumlaunch1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Perfume",
    "images": [
      "/perfume1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Perfume",
    "images": [
      "/perfume2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Perfume",
    "images": [
      "/perfume3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Scent Candle",
    "images": [
      "/scent-candle.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Sepatu",
    "images": [
      "/sepatu1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Ampoule",
    "images": [
      "/skincare-ampoule.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Ampoule",
    "images": [
      "/skincare-ampoule1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Facewashlaunch",
    "images": [
      "/skincare-facewashlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Facewashlaunch",
    "images": [
      "/skincare-facewashlaunch2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Facewashtestimoni",
    "images": [
      "/skincare-facewashtestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Moisturizer",
    "images": [
      "/skincare-moisturizer.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Moisturizer",
    "images": [
      "/skincare-moisturizer1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Moisturizer",
    "images": [
      "/skincare-moisturizer2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Moisturizerlaunch",
    "images": [
      "/skincare-moisturizerlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum10.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum4.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum5.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum6.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum7.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum8.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serum",
    "images": [
      "/skincare-serum9.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serumlaunch",
    "images": [
      "/skincare-serumlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serumlaunch",
    "images": [
      "/skincare-serumlaunch2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serumlaunch",
    "images": [
      "/skincare-serumlaunch3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serumtestimoni",
    "images": [
      "/skincare-serumtestimoni.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Serumtestimoni",
    "images": [
      "/skincare-serumtestimoni2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Sleepingmask",
    "images": [
      "/skincare-sleepingmask.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Toner",
    "images": [
      "/skincare-toner1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Toner",
    "images": [
      "/skincare-toner2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Toner",
    "images": [
      "/skincare-toner3.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincare Tonerlaunch",
    "images": [
      "/skincare-tonerlaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincarelaunch",
    "images": [
      "/skincarelaunch.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Skincarelaunch",
    "images": [
      "/skincarelaunch1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Sunscreen",
    "images": [
      "/sunscreen.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Sunscreen",
    "images": [
      "/sunscreen1.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Sunscreen",
    "images": [
      "/sunscreen2.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Tas",
    "images": [
      "/tas.webp"
    ]
  },
  {
    "type": "feed",
    "cat": "Konten Feed",
    "title": "Tas",
    "images": [
      "/tas1.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Babywash",
    "images": [
      "/carousel/babywash 2 slides/1.webp",
      "/carousel/babywash 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Bodylotion",
    "images": [
      "/carousel/bodylotion 3 slides/slide 1.webp",
      "/carousel/bodylotion 3 slides/slide 2.webp",
      "/carousel/bodylotion 3 slides/slide 3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Bodymist",
    "images": [
      "/carousel/bodymist 3 slides/1.webp",
      "/carousel/bodymist 3 slides/2.webp",
      "/carousel/bodymist 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Bodywash",
    "images": [
      "/carousel/bodywash 2 slides/1.webp",
      "/carousel/bodywash 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Cushion",
    "images": [
      "/carousel/cushion 2 slides/1.webp",
      "/carousel/cushion 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Difusser",
    "images": [
      "/carousel/difusser 3 slides/1.webp",
      "/carousel/difusser 3 slides/2.webp",
      "/carousel/difusser 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Facewash",
    "images": [
      "/carousel/facewash 3 slides/1.webp",
      "/carousel/facewash 3 slides/2.webp",
      "/carousel/facewash 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Hairclay",
    "images": [
      "/carousel/hairclay 2 slides/1.webp",
      "/carousel/hairclay 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 4 Slide",
    "title": "Hairoil",
    "images": [
      "/carousel/hairoil 4 slides/1.webp",
      "/carousel/hairoil 4 slides/2.webp",
      "/carousel/hairoil 4 slides/3.webp",
      "/carousel/hairoil 4 slides/4.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Kaos",
    "images": [
      "/carousel/kaos 2 slides/1.webp",
      "/carousel/kaos 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Lipstick",
    "images": [
      "/carousel/lipstick 2 slides/1.webp",
      "/carousel/lipstick 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Moisturizer",
    "images": [
      "/carousel/moisturizer 3 slides/1.webp",
      "/carousel/moisturizer 3 slides/2.webp",
      "/carousel/moisturizer 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 4 Slide",
    "title": "Moisturizer",
    "images": [
      "/carousel/moisturizer 4slides/1.webp",
      "/carousel/moisturizer 4slides/2.webp",
      "/carousel/moisturizer 4slides/3.webp",
      "/carousel/moisturizer 4slides/4.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Moisturizer",
    "images": [
      "/carousel/moisturizer2 3 slides/1.webp",
      "/carousel/moisturizer2 3 slides/2.webp",
      "/carousel/moisturizer2 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Parfum",
    "images": [
      "/carousel/parfum 2 slides/slide 1.webp",
      "/carousel/parfum 2 slides/slide 2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Parfum",
    "images": [
      "/carousel/parfum 3 slides/1.webp",
      "/carousel/parfum 3 slides/2.webp",
      "/carousel/parfum 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Serum",
    "images": [
      "/carousel/serum 3 slides/1.webp",
      "/carousel/serum 3 slides/2.webp",
      "/carousel/serum 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Serum",
    "images": [
      "/carousel/serum2 3 slides/1.webp",
      "/carousel/serum2 3 slides/2.webp",
      "/carousel/serum2 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Serum",
    "images": [
      "/carousel/serum3 2 slides/1.webp",
      "/carousel/serum3 2 slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 2 Slide",
    "title": "Sunscreen",
    "images": [
      "/carousel/sunscreen 2slides/1.webp",
      "/carousel/sunscreen 2slides/2.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Toner",
    "images": [
      "/carousel/toner 3 slides/1.webp",
      "/carousel/toner 3 slides/2.webp",
      "/carousel/toner 3 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Tumbler",
    "images": [
      "/carousel/tumbler 2 slides/1.webp",
      "/carousel/tumbler 2 slides/2.webp",
      "/carousel/tumbler 2 slides/3.webp"
    ]
  },
  {
    "type": "carousel",
    "cat": "Carousel 3 Slide",
    "title": "Tumbler",
    "images": [
      "/carousel/tumbler 3 slides/1.webp",
      "/carousel/tumbler 3 slides/2.webp",
      "/carousel/tumbler 3 slides/3.webp"
    ]
  }
];

export default WORKS;
